"""empty message

Revision ID: 650fdcc524ad
Revises: 4a332e4536d2
Create Date: 2017-05-23 22:51:38.152348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650fdcc524ad'
down_revision = '4a332e4536d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acl__permissions', sa.Column('for_all_objects', sa.Boolean(), nullable=True))
    op.create_unique_constraint('_oc__student_in_class_uc', 'oc__student_in_class', ['class_id', 'student_id'])
    op.create_unique_constraint('_oc__teacher_specialization_uc', 'oc__teacher_specialization', ['specialization_id', 'teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_oc__teacher_specialization_uc', 'oc__teacher_specialization', type_='unique')
    op.drop_constraint('_oc__student_in_class_uc', 'oc__student_in_class', type_='unique')
    op.drop_column('acl__permissions', 'for_all_objects')
    # ### end Alembic commands ###
